### PR TITLE
Monthly merge April 2024

### PR DESCRIPTION
**Pull request by slohse**
* updated ngi_reports, taca, taca_ngi_pipeline to latest
* updated CheckQC to v4.0.2
* updated sequencing report service to v1.5.0
* added nf-core/demultiplex to the deployment
* added `snpseq-metadata-service`

### CODE REVIEW

**Review by b97pla — APPROVED** [review]
the parts I know about (mainly snpseq-metadata) look good :+1:

**Review by FranBonath — COMMENTED** [review]
looks like you also update nf-core, would be good to add that to the list of updates, since it will warrant a verification.

**Comment by Aratz** [comment]
No I did not. What is expected from such validation? Are there examples from older protocols?

The new nf-core version fixes https://github.com/nf-core/tools/issues/2644, we can't have the new demultiplex pipeline if we don't update nf-core (although the service will still be able to run seqreports)

**Review by b97pla — APPROVED** [review]

**Comment by slohse** [comment]
Everything has been validated, merging :rocket:

**Pull request merged**
