### PR TITLE
Monthly May 2023

### PR DESCRIPTION
**Pull request by ssjunnebo**
Updates:

* Add kraken2
* Fixes to DDS runfolder deliveries with TACA
* MultiQC_NGI to 0.7.1
* TACA to latest
* nfcore
   * Ampliseq to 2.5.0
   * Viralrecon to 2.6.0
   * RNAFusion to 2.3.4
   * NanoSeq to 3.1.0
   * SCRNASeq to 2.3.0

### CODE REVIEW

**Comment by aanil** [comment]
Should this(https://github.com/NationalGenomicsInfrastructure/miarka-provision/pull/178) be merged to monthly before this one?

**Comment by matrulda** [comment]
@aanil It is merged now :) Thanks for waiting!

**Review by aanil — APPROVED** [review]
👍

**Review by b97pla — APPROVED** [review]
:+1: great work!

**Pull request merged**
