### PR TITLE
Update multiqc to 1.13, taca to latest version and taca_ngi_pipeline to further support DDS deliveries

### PR DESCRIPTION
**Pull request by aanil**

### CODE REVIEW

**Review by ssjunnebo — APPROVED** [review]
👍

**Review by slohse — APPROVED** [review]

**Comment by b97pla** [comment]
there's no breaking changes in `tact_ngi_pipeline`, right?

**Comment by aanil** [comment]
> there's no breaking changes in `tact_ngi_pipeline`, right?

No, there should be no breaking changes in taca_ngi_pipeline.

**Review by b97pla — APPROVED** [review]
:+1:

**Pull request merged**
