### PR TITLE
Updated checkQC version

### PR DESCRIPTION
**Pull request by nkongenelly**
Update checkQC version in arteria-checkqc-ws role to v4.0.2

### CODE REVIEW

**Comment by Aratz** [comment]
Looks good, the only thing is that the PR should target the `monthly` branch (instead of `main`)

**Comment by nkongenelly** [comment]
Oh, thanks for that. I have now changed that.

**Review by matrulda — APPROVED** [review]

**Comment by matrulda** [comment]
@slohse Just want to double-check if it's OK to merge this to monthly?

**Comment by slohse** [comment]
Yes, go ahead.

**Pull request merged**
