### PR TITLE
Monthly

### PR DESCRIPTION
**Pull request by ssjunnebo**

### CODE REVIEW

**Review by aanil — APPROVED** [review]
👍

**Comment by Aratz** [comment]
Is this gonna go into production? We still need to validate the changes from [d127a19](https://github.com/NationalGenomicsInfrastructure/miarka-provision/pull/92/commits/d127a19f7a2f4af058f5af773a6d8702a0006abe) before that :/

**Comment by ssjunnebo** [comment]
> 

Yes, the plan was to deploy this to production today. How long would you need for the validation?

**Comment by Aratz** [comment]
At least a week, I don't think that was supposed to go into `monthly` in the first place :grimacing: I guess the easiest would be to `git revert` that commit for now so that it does not affect this deployment. What do you think @b97pla?

**Pull request merged**
