### PR TITLE
Add Nextflow Tower config

### PR DESCRIPTION
**Pull request by ewels**
Added the config required to _monitor_ Nextflow runs at https://ngi-tower.scilifelab.se/ (launched the traditional way on the CLI, not launch via Tower)

Requires some additional config:

- Site-specific workspace IDs set in the relevant configs as `tower_workspace_id`
    - These are the `Id` shown for each node at https://ngi-tower.scilifelab.se/orgs/NGI/workspaces
    - When set, will collect all runs in the node's workspace, eg. https://ngi-tower.scilifelab.se/orgs/NGI/workspaces/NGI-Stockholm/watch
- Person-specific Tower access tokens _(outside of miarka-provision)_
    - Each person needs to log in to NGI-Tower and go to https://ngi-tower.scilifelab.se/tokens to create a new token
    - In `.bashrc` or similar, add `export TOWER_ACCESS_TOKEN=<YOUR ACCESS TOKEN>`

Once this is done ☝🏻 no further config is required. Existing launch commands can remain unchanged.

✅  Just tested on Miarka with my custom version of Nextflow (version `21.12.1-edge build 5654`) and it worked first time.
✅  Also tried with `/vulpes/ngi/staging/220401.e758cb1/sw/nextflow/nextflow` (version `21.04.3 build 5563`) and it also worked first time.

That was for a _very_ basic pipeline, but hopefully holds true for all Nextflow pipelines 🤞🏻

### CODE REVIEW

**Comment by ewels** [comment]
NB: Once merged and deployed, pipeline launches will fail if `TOWER_ACCESS_TOKEN` is not set somehow:

```console
$ /vulpes/ngi/staging/220401.e758cb1/sw/nextflow/nextflow run minimal_pipeline.nf
N E X T F L O W  ~  version 21.04.3
Launching `minimal_pipeline.nf` [fabulous_thompson] - revision: d3a65fa206
Missing Nextflow Tower access token -- Make sure there's a variable TOWER_ACCESS_TOKEN in your environment
```

Not an issue, just means that everyone needs to have set this up by the time the deployment goes live. And if anyone is still running with funk accounts etc, needs consideration 👍🏻

**Comment by ewels** [comment]
> Not an issue, just means that everyone needs to have set this up by the time the deployment goes live.

This also means that anyone running Nextflow _has_ to have an account set up at NGI-Tower of course. Which may not be the case currently, but should be easy / fast to sort out.

**Comment by ewels** [comment]
Steps to test manually:

1. Log in to https://ngi-tower.scilifelab.se with the "OpenID Connect" button, followed by GitHub auth _(if you get an error, let me know what your primary email address is for your GitHub account)_
2. Go to https://ngi-tower.scilifelab.se/orgs/NGI/workspaces - you should see a list of _Workspaces_. Make a note of the `Id` of the workspace named after your NGI node.
3. Go to https://ngi-tower.scilifelab.se/tokens and generate a new token (and copy this)
5. Set the following environment variables in your `~/.bashrc` file (or just your shell or wherever):
    ```bash
    export TOWER_ACCESS_TOKEN="<YOUR_ACCESS_TOKEN>"
    export TOWER_WORKSPACE_ID="<WORKSPACE_ID>"
    export TOWER_API_ENDPOINT="https://ngi-tower.scilifelab.se/api"
    ```
6. Run a Nextflow pipeline in the normal way, but with the additional flag `-with-tower`

If you prefer, you can put this stuff in your home directory in a config file instead, called `~/.nextflow/config` (the file is called `config`, no file extension). With this method, you don't need the `-with-tower` flag - the Nextflow command remains totally unchanged.

```nextflow
tower {
  accessToken = '<YOUR TOKEN>'
  workspaceId = '<YOUR WORKSPACE ID>'
  endpoint = 'https://ngi-tower.scilifelab.se/api'
  enabled = true
}
```

If everything works well, you should get a log message from Nextflow with a URL to monitor the execution on Tower. You should also see your run show up in the _Runs_ tab for your workspace.

Once this PR is merged, the workspace ID and API endpoint will be set in the deployment config, so it's only the `TOWER_ACCESS_TOKEN` that you'll need to set yourself (as this is personal to you). Also there will be no need for the `-with-tower` flag when running Nextflow.

**Review by b97pla — APPROVED** [review]
:+1: great work @ewels and thanks for the detailed instructions, this looks straightforward on our part.

If possible, it would be great if this PR could go to the monthly branch instead

**Comment by b97pla** [comment]
regarding the `TOWER_ACCESS_TOKEN` in the environment, will the pipeline launch also fail if the token is invalid or is it just required that the variable exists?

i.e. would it be possible to catch this error by just doing e.g. `export TOWER_ACCESS_TOKEN=changeme` in the common sourced environment files?

**Comment by ewels** [comment]
Branch changed 👍🏻 I have a feeling that the run will fail if the token is not valid. I'm not 100% sure though.

**Comment by ewels** [comment]
Note that I kind of think it's a good thing that it fails! I think it would be quite easy to let it slide otherwise and for us to start missing runs. Failing fast and obviously should hopefully mean it's obvious and immediately sorted. It also forces everyone to set up from day 1.

**Comment by b97pla** [comment]
:+1: great, thanks for this

**Pull request merged**
